### ISSUE TITLE
The "Releases Wiki Page" link is dead

### ISSUE THREAD

**Issue by karol-majewski** [Glavin001/tslint-clean-code#47]
The _Releases Wiki Page_ link points to https://github.com/Microsoft/tslint-clean-code/wiki/Releases which doesn't exist. I guess no link or the [original one](https://github.com/Microsoft/tslint-microsoft-contrib/wiki/Releases) should be used instead.

**Comment by Glavin001** [comment]
Great find! I think this can be removed now.

Pull Requests welcome. Thanks!
