### ISSUE TITLE
References to native Array class methods are incorrect

### ISSUE THREAD

**Issue by karol-majewski** [Glavin001/tslint-clean-code#48]
I know it's just an academic detail, but there is no `Array.map`, `Array.forEach` etc. — there's either prototype methods (`Array.prototype.map`) or instance methods (`[].map`).

https://github.com/Glavin001/tslint-clean-code/blob/f1ca6663d30f8bc8dbeb6778cf85d7c45805c1f8/src/noMapWithoutUsageRule.ts#L15

But since it's consistent accross the repository, I guess you can ignore it 👍.

**Comment by Glavin001** [comment]
I was also thinking about this the other day. Glad someone else is paying attention to the details 😉. I think changing the message to be correct would be worth while. Pull Requests welcome! Thank you!

**Comment by Glavin001** [comment]
Published to v0.2.5
